runtime: php
env: flex

handlers:
- url: /.*
  script: app.php

runtime_config:
  document_root: .

#[START env]
env_variables:
    # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
    # values obtained when configuring your Cloud SQL instance.
    POSTGRES_USER: 'postgres'
    POSTGRES_PASSWORD: '2gK8566u2NcohymI'
    POSTGRES_DSN: pgsql:dbname=crypto;host=/cloudsql/pro-bruin-145004:australia-southeast1:crypto
#[END env]

#[START cloudsql_settings]
# Use the connection name obtained when configuring your Cloud SQL instance.
beta_settings:
    cloud_sql_instances: "pro-bruin-145004:australia-southeast1:crypto"
#[END cloudsql_settings]
